### ISSUE TITLE
现在已经导出不了了。

### ISSUE THREAD

**Issue by xuanyuan1hao** [wesley2012/YoudaoNoteExport#2]
我这里测试，现在会生成json文件及其一个xml文件，没有生成对应的docx文件

**Comment by gaory1** [comment]
刚改了一下，可以了

**Comment by xuanyuan1hao** [comment]
已经测试OK，能否修改成导出pdf文件呢，有道的note文件不是通用的。

**Comment by gaory1** [comment]
有道的网站只能导出WORD，不能导出PDF，所以不行呢。你可以尝试自己转。libreoffice貌似有这样的命令。

**Comment by gaory1** [comment]
https://michalzalecki.com/converting-docx-to-pdf-using-python/

**Comment by xuanyuan1hao** [comment]
这里导出的是类似如下的xml文件，不是docx的word文件
<note xmlns="http://note.youdao.com" file-version="0" schema-version="1.0.3">
<head/>
<body>
<para>
<coId>5546-1510215400053</coId>
<text>一、检索引擎部分支持：</text>
<inline-styles>
<bold>
<from>0</from>
<to>11</to>
<value>true</value>
</bold>
</inline-styles>
<styles/>
</para>
<para>

**Comment by gaory1** [comment]
$ file WEB77b826a211392f2c41809594f64188c5.docx
WEB77b826a211392f2c41809594f64188c5.docx: Microsoft OOXML
是WORD嘛

**Comment by gaory1** [comment]
导出命令是这样的：
python main.py 用户名 密码 tmp/ docx

**Comment by xuanyuan1hao** [comment]
sorry，我这里用了如下命令
python main.py 用户名 密码 ./note

**Comment by xuanyuan1hao** [comment]
CED7BD2595FB421F848AA21396F94104 面试
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    sess.getAll(saveDir, doc_type)
  File "main.py", line 117, in getAll
    self.getFileRecursively(rootId, saveDir, doc_type)
  File "main.py", line 103, in getFileRecursively
    os.mkdir(subDir)
WindowsError: [Error 3] : u'./note/\u9762\u8bd5'


windows下导出word是不行的。
python main.py 用户名 密码  ./note docx

**Comment by gaory1** [comment]
这是啥问题啊，跟Unicode有关？我这里是Ubuntu。。。

**Comment by gaory1** [comment]
http://irootlee.com/python_mkdir/
是不是note目录没有预先创建？

**Comment by xuanyuan1hao** [comment]
yes，but after it mkdir note
ERROR like this
getRoot:{"canTryAgain":false,"scope":"SECURITY","error":"207","message":"Message
[AUTHENTICATION_FAILURE]: User token must be authenticated.","objectUser":null}
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    sess.getAll(saveDir, doc_type)
  File "main.py", line 116, in getAll
    rootId = self.getRoot()
  File "main.py", line 53, in getRoot
    return jsonObj['fileEntry']['id']
KeyError: 'fileEntry'

**Comment by gaory1** [comment]
哈哈，这个错是因为登录太频繁，被有道封了。“请稍后再试～”
或者你用浏览器手工登录一下，输入验证码就解封了。

2018-07-09 15:18 GMT+08:00 xuanyuan1hao <notifications@github.com>:

**Comment by xuanyuan1hao** [comment]
嗯，的确是可以导出docx文件了，但是中文的docx打开全部乱码。。。

**Comment by gaory1** [comment]
我这里没有遇到，中文可以正常显示。我用的LibreOffice。有没有不敏感的文件发出来看看

**Comment by luohc2004** [comment]
可能是你的笔记名里有不能做windows文件名的非法字符吧。另外，我把写入docx文件的方法参数 open('%s/%s(dir,id)','w')改成open('%s/%s(dir,id)','wb')二进制写入才能打开，估计还是win下字符编码的问题
