### ISSUE TITLE
KeyError: 'fileEntry'

### ISSUE THREAD

**Issue by jdk6979** [wesley2012/YoudaoNoteExport#5]
authenticated失败？

环境
Ubuntu 16.04 + Python 2.7

(py27)  python main.py email password . docx

<RequestsCookieJar[<Cookie JSESSIONID=aaakO1HFTmPqjc1RARjJw for note.youdao.com/>, <Cookie OUTFOX_SEARCH_USER_ID=x@10.120.182.16 for note.youdao.com/auth>, <Cookie OUTFOX_SEARCH_USER_ID=-x@10.120.182.16 for note.youdao.com/login/acc/pe>, <Cookie YNOTE_URS_VERIFY=x for note.youdao.com/login/acc/urs/verify>]>
getRoot:{"canTryAgain":false,"scope":"SECURITY","error":"207","message":"Message[AUTHENTICATION_FAILURE]: User token must be authenticated.","objectUser":null}
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    sess.getAll(saveDir, doc_type)
  File "main.py", line 116, in getAll
    rootId = self.getRoot()
  File "main.py", line 53, in getRoot
    return jsonObj['fileEntry']['id']
KeyError: 'fileEntry'

**Comment by allenzhung** [comment]
导出docx我也遇到同样的错误，但是可以导出xml格式的，但是又看不懂

**Comment by gaory1** [comment]
还是没复现出来.会不会是密码包含特殊字符啊...

@allenzhung 其中我就是导出xml的, 因为内容简单, 所以把标签去掉就可以了. 
[getNoteText.txt](https://github.com/wesley2012/YoudaoNoteExport/files/3217646/getNoteText.txt)

**Comment by Fiona-zhu** [comment]
第一次导出docx没问题，后来导出docx我也遇到同样的错误～  好奇怪～
getRoot:{"canTryAgain":false,"scope":"SECURITY","error":"207","message":"Message[AUTHENTICATION_FAILURE]: User token must be authenticated.","objectUser":null}
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    sess.getAll(saveDir, doc_type)
  File "main.py", line 116, in getAll
    rootId = self.getRoot()
  File "main.py", line 53, in getRoot
    return jsonObj['fileEntry']['id']
KeyError: 'fileEntry'

**Comment by gaory1** [comment]
Message[AUTHENTICATION_FAILURE
看这一句是密码错了还是被封了

发自我的 iPhone

> 在 2019年11月12日，09:56，Fiona-zhu <notifications@github.com> 写道：
> 
> Message[AUTHENTICATION_FAILURE

**Comment by luohc2004** [comment]
谢谢owner的代码。这个就是登陆不成功导致的。应该就是网易那边要求验证码验证了。我这边只在要网页版上登录一下，输入验证码，python这边再运行就可以登陆了。运行几次，再登陆不成功，网页版退出再登录一下，主要是输验证码。
