### ISSUE TITLE
importError

### ISSUE THREAD

**Issue by pasv0001** [wesley2012/YoudaoNoteExport#6]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import requests
ImportError: No module named requests

请问这个怎么解决啊？本人对python没什么了解。我的系统版本是ubuntu16.04;python版本是2.7.12
这个插件很有用，感谢你的付出！

**Comment by gaory1** [comment]
抱歉没注意看邮箱...这个requests用pip安装就好了吧

发自我的 iPhone

**Comment by pasv0001** [comment]
sudo apt install python-pip
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python-pip 已经是最新版 (8.1.1-2ubuntu0.4)。

你好，我检查了下，好像已经安装了pip了，是安装这个包吗？谢谢啦

**Comment by gaory1** [comment]
pip intall requests
