### ISSUE TITLE
Incorrect title

### ISSUE THREAD

**Issue by Fiona-zhu** [wesley2012/YoudaoNoteExport#7]
The title of each notes is not correct,  can i do anything to get the right titles?
Titles are like "B28E2F39481A4904AA75014D00AB8A9E","B6822D15AC69468CA7787E6DBB38DDED" and so on.
At last, THX for your contribution :D

**Comment by gaory1** [comment]
It's in the json file. I use this statement to extract the title:
title = jsonObj['fileEntry']['name'].replace('.note', '')

**Comment by Fiona-zhu** [comment]
Thanks for ur reply :D
I wrote another shell to rename my titles which include some **chinese**,like:

# -*- coding: utf-8 -*-
import requests
import sys
import time
import hashlib
import os
from requests.cookies import create_cookie
import json
import re
reload(sys)  
sys.setdefaultencoding('utf8')

def get_files(path, rule):
    all = []
    for fpathe,dirs,fs in os.walk(path):   # os.walk获取所有的目录
        for f in fs:
            filename = os.path.join(fpathe,f)
            if filename.endswith(rule):  # 判断是否是".json"结尾
                all.append(filename)
    return all

def list_file(root,postfix=''):
    file_reserved=[]
    files=os.listdir(root)
    for item in files:
        if os.path.isfile(os.path.join(root,item)):
            if item.endswith(postfix):
                file_reserved.append(os.path.join(root,item))
        else:
            if os.path.isdir(os.path.join(root,item)):
                file_reserved.append(list_file(os.path.join(root,item),postfix))
    return file_reserved

path = 'your_path/YoudaoNoteExport/notes'
file_reserved=[]
all_jsons = get_files(path,'.json')

for one_json in all_jsons:
    json_data = open(one_json).read()
    json_text = json.loads(json_data)
    name = json_text['fileEntry']['name']
    # print(json_text['fileEntry']['name'])
    old_path = os.path.split(one_json)

    same_docx =  old_path[0]+os.sep+os.path.splitext(old_path[1])[0]+'.docx'
    newname = old_path[0]+os.sep+name+'.docx'
    # print(same_docx,newname)
    if(os.path.exists(same_docx)):
        os.rename(same_docx,newname)
    #.decode('gbk').encode('utf-8')

Hope it can be helpful for others :D

**Comment by gaory1** [comment]
Yeah. I'm sure it's helpful. But there is still something to handle. For example what if the name has special characters in it...

**Comment by luohc2004** [comment]
yeah...I replaced all illegal characters for windows file name to completely drag out my note since 2015.
