### ISSUE TITLE
请教一下repo主，前面登录的过程是怎么抓的

### ISSUE THREAD

**Issue by luohc2004** [wesley2012/YoudaoNoteExport#8]
#感觉这个过程好复杂啊，如果用fiddler要看好久才能搞清楚。有没有什么工具能方便的自动生成这些代码？还是就自己一点点抓包的？

**Comment by luohc2004** [comment]
我还有一个问题，多年前的老笔记，格式可能不通用(在网页版打开时显示要转换格式），以docx方式下载不到：{"canTryAgain":false,"scope":"PREVIOUS_EXCEPTION","error":"213","message":"Message[DATA_TRANSMISSION_FAILURE]: Failed get inputStream noteId=61f46f1dd47zzzzzzzzzz7d43901f3249a6,userToken=xxxxxxxxxxxxxx"}

**Comment by gaory1** [comment]
其实我自己的笔记是用XML导出的，纯文字，木有图片。DOCX是别人写的，我没用过...
那些链接是从Chrome里面通过Web页面登录笔记后看到的，跟fiddler应该是差不多的

**Comment by luohc2004** [comment]
谢谢，折腾完，还有一半的笔记没下来....很奇怪，在网页客户端访问到老笔记时显示转换格式，之后就能下载到，可是我用python request先访问一遍之后，还是下不到docx...
